export const mockSnapshot = {
  generatedAt: null,
  progress: {
    mission: null,
    progress: {
      total: 0,
      done: 0,
      running: 0,
      blocked: 0,
      percent: 0,
    },
  },
  missionSummary: null,
  meta: {
    missionCount: 0,
    agentCount: 0,
    activeAgentCount: 0,
    taskCount: 0,
    completedTaskCount: 0,
    blockedTaskCount: 0,
    eventCount: 0,
    notificationCount: 0,
    runningTaskId: null,
    runningTaskTitle: null,
  },
  activeMission: null,
  missions: [],
  agents: [],
  tasks: [],
  intakeRequests: [],
  hireRequests: [],
  stream: {
    events: [],
    notifications: [],
  },
}
